after-startup-command = [
    # https://github.com/FelixKratz/JankyBorders
    'exec-and-forget borders "active_color=gradient(top_left=0xee33ccff,bottom_right=0xee00ff99)" inactive_color=0xaa595959 width=6.5',
    'exec-and-forget aerospace layout tiles'
]

start-at-login = false

# See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

automatically-unhide-macos-hidden-apps = false

[gaps]
    inner.horizontal = 10
    inner.vertical =   10
    outer.left =       10
    outer.bottom =     10
    outer.top =        10
    outer.right =      10

[mode.main.binding]
 
    # See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
    cmd-shift-enter = 'exec-and-forget osascript $HOME/.config/aerospace/wezterm.applescript'

    # See: https://nikitabobko.github.io/AeroSpace/commands#fullscreen
    cmd-shift-space = 'fullscreen'

    # See: https://nikitabobko.github.io/AeroSpace/commands#focus
    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    # See: https://nikitabobko.github.io/AeroSpace/commands#move
    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    # See: https://nikitabobko.github.io/AeroSpace/commands#resize
    cmd-shift-up = 'resize smart +25'
    cmd-shift-down = 'resize smart -25'

    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace
    cmd-alt-1 = 'workspace 1'
    cmd-alt-2 = 'workspace 2'
    cmd-alt-3 = 'workspace 3'
    cmd-alt-4 = 'workspace 4'

    # See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
    cmd-shift-1 = 'move-node-to-workspace 1'
    cmd-shift-2 = 'move-node-to-workspace 2'
    cmd-shift-3 = 'move-node-to-workspace 3'
    cmd-shift-4 = 'move-node-to-workspace 4'

    # See: https://nikitabobko.github.io/AeroSpace/commands#join-with
    cmd-shift-h = ['join-with left', 'mode main']
    cmd-shift-j = ['join-with down', 'mode main']
    cmd-shift-k = ['join-with up', 'mode main']
    cmd-shift-l = ['join-with right', 'mode main']

[exec.env-vars]
PATH = '/usr/local/bin/:/opt/homebrew/bin:${PATH}'
