"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$package\
$c\
$dotnet\
$golang\
$helm\
$java\
$kotlin\
$gradle\
$maven\
$lua\
$nodejs\
$python\
$ruby\
$rust\
$terraform\
$fill\
$cmd_duration\
$time\
$line_break\
$character"""

add_newline = false
palette = "catppuccin_mocha"

[fill]
symbol = ' '

[directory]
truncation_length = 1
truncation_symbol = '…/'
truncate_to_repo = false
style = 'bold fg:#01b1ff'
before_repo_root_style = 'bold fg:#067fa4'
repo_root_style = 'bold fg:#01b1ff'
disabled = false

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
style = "bold green"
disabled = false

[git_status]
format = "[[($conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style) "
style = "cyan"
untracked = "?${count}"
modified = "!${count}"
staged = "+${count}"
renamed = "~${count}"
deleted = "-${count}"
stashed = "≡"

[package]
format = '[$symbol$version]($style) '

[java]
format = '[$symbol$version]($style) '

[docker_context]
format = '[$symbol$context]($style) '

[time]
format = '[$time]($style) '
style = 'fg:#5c8283'
disabled = false

[cmd_duration]
format = '[$duration]($style) '
style = 'fg:#85835e'
disabled = false

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
