"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$character"""

right_format = """
$username\
$hostname\
$docker_context\
$package\
$c\
$dotnet\
$golang\
$helm\
$java\
$kotlin\
$gradle\
$maven\
$lua\
$nodejs\
$python\
$ruby\
$rust\
$scala\
$terraform\
$cmd_duration\
$time"""

add_newline = false
palette = "catppuccin_mocha"

[directory]
truncation_length = 3
truncation_symbol = '…/'
truncate_to_repo = false
style = 'bold fg:#01b1ff'
before_repo_root_style = 'bold fg:#067fa4'
repo_root_style = 'bold fg:#01b1ff'
disabled = false

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
style = "bold green"
disabled = false

[package]
format = '[$symbol$version]($style) '

[java]
format = '[$symbol$version]($style) '

[docker_context]
format = '[$symbol$context]($style) '

[git_status]
format = '[$all_status$ahead_behind ]($style)'
ahead = "⇡${count}"
diverged = "⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
modified = "~${count}"
untracked = "?${count}"
staged = "+${count}"
stashed = "≡${count}"

[time]
format = '[$time]($style) '
style = 'fg:#5c8283'
disabled = false

[cmd_duration]
format = '[$duration]($style) '
style = 'fg:#85835e'
disabled = false

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
